// Code generated by "exporter". DO NOT EDIT.
package a

import (
	"example.com/example/a/ab"
)

// Sum adds two numbers of a generic type T which can be either int or float64.
func Sum[T int | float64](a T, b T) (r T) {
	return ab.Sum(a, b)
}

// SumAll adds a variadic number of values of a generic type T which can be either int or float64.
func SumAll[T int | float64](values ...T) T {
	return ab.SumAll(values...)
}
