// Code generated by "exporter". DO NOT EDIT.
package a

import (
	"example.com/example/a/aa"
)

type (

	// MyEnum is an example enumeration type
	MyE = aa.MyEnum
)

var (
	MyVar = aa.MyVar // MyVar
)

const (
	EV1 = aa.EnumValue1 // EnumValue1

	EV2 = aa.EnumValue2 // EnumValue2

	EV3 = aa.EnumValue3 // EnumValue3

	// EnumValue4 comment
	EV4 = aa.EnumValue4 // Comment
)

// SayHello prints a greeting message using MyVar.
func SayHello() {
	aa.SayHello()
}
